// <auto-generated />
using System;
using MaClassePA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaClassePA.Migrations
{
    [DbContext(typeof(ClassesDbContext))]
    partial class ClassesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaClassePA.Models.ClasseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("MaClassePA.Models.MatiereModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClasseId")
                        .HasColumnType("int");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("MaClassePA.Models.RessourceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatiereId");

                    b.ToTable("Ressources");
                });

            modelBuilder.Entity("MaClassePA.Models.VisitesCounter<MaClassePA.Models.ClasseModel>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<long>("Visites")
                        .HasColumnType("bigint");

                    b.Property<int>("VisitesTrackerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitesTrackerId")
                        .IsUnique();

                    b.ToTable("VisitesCounters_Classes");
                });

            modelBuilder.Entity("MaClassePA.Models.VisitesCounter<MaClassePA.Models.MatiereModel>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<long>("Visites")
                        .HasColumnType("bigint");

                    b.Property<int>("VisitesTrackerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitesTrackerId")
                        .IsUnique();

                    b.ToTable("VisitesCounter<MatiereModel>");
                });

            modelBuilder.Entity("MaClassePA.Models.VisitesCounter<MaClassePA.Models.RessourceModel>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<long>("Visites")
                        .HasColumnType("bigint");

                    b.Property<int>("VisitesTrackerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitesTrackerId")
                        .IsUnique();

                    b.ToTable("VisitesCounter<RessourceModel>");
                });

            modelBuilder.Entity("MaClassePA.Models.MatiereModel", b =>
                {
                    b.HasOne("MaClassePA.Models.ClasseModel", "Classe")
                        .WithMany("Matieres")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("MaClassePA.Models.RessourceModel", b =>
                {
                    b.HasOne("MaClassePA.Models.MatiereModel", "Matiere")
                        .WithMany("Ressources")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("MaClassePA.Models.VisitesCounter<MaClassePA.Models.ClasseModel>", b =>
                {
                    b.HasOne("MaClassePA.Models.ClasseModel", "VisitesTracker")
                        .WithOne("VisitesCounter")
                        .HasForeignKey("MaClassePA.Models.VisitesCounter<MaClassePA.Models.ClasseModel>", "VisitesTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitesTracker");
                });

            modelBuilder.Entity("MaClassePA.Models.VisitesCounter<MaClassePA.Models.MatiereModel>", b =>
                {
                    b.HasOne("MaClassePA.Models.MatiereModel", "VisitesTracker")
                        .WithOne("VisitesCounter")
                        .HasForeignKey("MaClassePA.Models.VisitesCounter<MaClassePA.Models.MatiereModel>", "VisitesTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitesTracker");
                });

            modelBuilder.Entity("MaClassePA.Models.VisitesCounter<MaClassePA.Models.RessourceModel>", b =>
                {
                    b.HasOne("MaClassePA.Models.RessourceModel", "VisitesTracker")
                        .WithOne("VisitesCounter")
                        .HasForeignKey("MaClassePA.Models.VisitesCounter<MaClassePA.Models.RessourceModel>", "VisitesTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitesTracker");
                });

            modelBuilder.Entity("MaClassePA.Models.ClasseModel", b =>
                {
                    b.Navigation("Matieres");

                    b.Navigation("VisitesCounter");
                });

            modelBuilder.Entity("MaClassePA.Models.MatiereModel", b =>
                {
                    b.Navigation("Ressources");

                    b.Navigation("VisitesCounter");
                });

            modelBuilder.Entity("MaClassePA.Models.RessourceModel", b =>
                {
                    b.Navigation("VisitesCounter");
                });
#pragma warning restore 612, 618
        }
    }
}
